# Generated by Django 3.2.8 on 2022-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=50)),
                ('EventImg', models.ImageField(upload_to='uploads/eventimg/')),
                ('EventDesc', models.CharField(max_length=200)),
                ('EventType', models.CharField(choices=[('Tech', 'Technical'), ('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('fun', 'Entertainment'), ('others', 'Others')], max_length=20)),
                ('EventCost', models.IntegerField()),
                ('EventDuration', models.CharField(choices=[('1 day', '1 day'), ('2 days', '2 days'), ('3 days', '3 days')], max_length=10)),
                ('EventStartDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudRegData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
