# Generated by Django 3.2.8 on 2022-02-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_studentenrolledevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrolledevents',
            name='EStartDate',
            field=models.CharField(max_length=50),
        ),
    ]
