# Generated by Django 3.2.8 on 2022-02-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0003_alter_studentenrolledevents_estartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrolledevents',
            name='ContactNo',
            field=models.BigIntegerField(),
        ),
    ]
