# Generated by Django 3.2.8 on 2022-02-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_alter_studentenrolledevents_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrolledevents',
            name='EName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.addevents'),
        ),
    ]
